# Julia quickstart

We provide an overview of basic Julia functionality. The source code for this document is available on [GitHub](https://github.com/eomii/JuliaQuickstart). Some notable concepts not covered in this guide include the [type system](https://docs.julialang.org/en/v1/manual/types/), [variable scopes](https://docs.julialang.org/en/v1/manual/variables-and-scoping/), [array broadcasting](https://docs.julialang.org/en/v1/manual/arrays/#Broadcasting), [module imports](https://docs.julialang.org/en/v1/manual/modules/), and [exception handling](https://docs.julialang.org/en/v1/manual/control-flow/#Exception-Handling).

## Printing output

Use `print` to print a canonical text representation of your input. You will often want to use `println`, which appends a newline `\n` to your output.

> Note: This document contains some mathematical symbols, such as `∈`. We can write these symbols in Julia-enabled editors and the Julia REPL by entering their $\LaTeX$ representation followed by a tab. E.g. `A ∩ B = ∅` was input as `A \cap-tab B = \emptyset-tab`.

In [1]:
print("Hello, World!\n")
println("Hello, World!")
println("The above line printed the newline automatically.")
println("A and B are disjunct if A ∩ B = ∅.")

Hello, World!
Hello, World!
The above line printed the newline automatically.
A and B are disjunct if A ∩ B = ∅.


## Comments

Use `#` for an inline comment. Use `#=` and `=#` for multiline comments.

In [2]:
# This is a comment.

#=
This is
a multiline comment
=#

## Strings

Strings are denoted via single quotes `"` or triple quotes `"""`, which differ in indentation behavior.

In [3]:
println("This is a string.")
println("This is
    an indented string.")
println("""This is another string.""")
println("""This is
    another indented string.""")

This is a string.
This is
    an indented string.
This is another string.
This is
another indented string.


Contrary to many other languages, Julia uses `*` instead of `+` for string concatenation. The number of characters in a string `S` is retrievable via `length(S)`.

In [4]:
println("This is " * "a " * "concatenated string.")
println(length("1 2 ∅ c"))  # Spaces are characters, too.

This is a concatenated string.
7


## Numbers

Below is the type tree of the subtypes of `Number`.

In [5]:
"Print the type tree of a Type."
function typetree(T::Type, indent=0::Int64)::Nothing
    println("\t" ^ indent, T)
    for t in subtypes(T)
        typetree(t, indent+1)
    end
end
typetree(Number)

Number
	Complex
	Real
		AbstractFloat
			BigFloat
			Float16
			Float32
			Float64
		AbstractIrrational
			Irrational
		Integer
			Bool
			Signed
				BigInt
				Int128
				Int16
				Int32
				Int64
				Int8
			Unsigned
				UInt128
				UInt16
				UInt32
				UInt64
				UInt8
		Rational


Julia will use types `Int64` and `Float64` for default numerical inputs.

In [6]:
println(typeof(2))
println(typeof(2.))
println(typeof(2.0))

Int64
Float64
Float64


Standard binary operators will convert input and output types in the way you would expect.

In [7]:
a, b = 3, 2
println("Addition:\t a + b = ", a + b)
println("Multiplication:\t a * b = ", a * b)
println("Subtraction:\t a - b = ", a - b)
println("Division:\t a / b = ", a / b)
println("Exponentiation:\t a ^ b = ", a ^ b)
println("Modulo op: \t a % b = ", a % b)
println("Comparison: \t a < b = ", a < b)
println("Comparison: \t a > b = ", a > b)
println("Comparison: \t a <= b = ", a <= b)
println("Comparison: \t a <= b = ", a >= b)
println("Comparison: \t a == b = ", a == b)
println("Comparison: \t a != b = ", a != b)

Addition:	 a + b = 5
Multiplication:	 a * b = 6
Subtraction:	 a - b = 1
Division:	 a / b = 1.5
Exponentiation:	 a ^ b = 9
Modulo op: 	 a % b = 1
Comparison: 	 a < b = false
Comparison: 	 a > b = true
Comparison: 	 a <= b = false
Comparison: 	 a <= b = true
Comparison: 	 a == b = false
Comparison: 	 a != b = true


## Variables

We have a rather high degree of freedom for variable names. We can assign values to a variable via `=`. We refer to the [official documentation](https://docs.julialang.org/en/v1/manual/variables/#Allowed-Variable-Names) for a specification of allowed variable names.

In [8]:
x = 1
こんにちは = "Hello"
δ = 1.0
α̂₂ = 5
println(x)
println(こんにちは)
println(δ)
println(α̂₂)

1
Hello
1.0
5


We may insert variable values in a template-like manner into strings via `$( )`.

In [9]:
greeting = "こんにちは"
println("$(greeting) is a greeting.")

こんにちは is a greeting.


## Control flow

Generally, control structures end with an `end` keyword. Below are some examples for if-else statements. We may use the `elseif` keyword to abbreviate `else (if ... end)`.

In [10]:
minimum_age = 16 
my_age = 25
if my_age >= minimum_age 
    println("Old enough to drink beer.")  # Only in Germany.
end

Old enough to drink beer.


In [11]:
my_age -= 10
if my_age >= minimum_age 
    println("Old enough to drink beer.") # Only in Germany.
else 
    println("Not allowed to drink beer.")   
end

Not allowed to drink beer.


In [12]:
parents_take_care_of_you_age = 14
if my_age >= minimum_age 
    println("Old enough to drink beer.")
elseif my_age >= parents_take_care_of_you_age
    println("Only with parents.")  # Good old German beer laws.    
else 
    println("Not allowed to drink beer.")   
end

Only with parents.


While-loops use a similar syntax. We may use the `break` keyword to break out of a control structure.

In [13]:
while true
    println("This loop only runs once.")
    break
end

This loop only runs once.


For-loops iterate over itarable values which we will explain more thoroughly in a later section. The syntaxes `for a = A`, `for a ∈ A` and `for a in A` are equivalent. The [iteration reference documentation](https://docs.julialang.org/en/v1/manual/interfaces/#man-interface-iteration) explains how for-loops are translated to while-loops internally.

In [14]:
A = 1:4  # Define a UnitRange containing values 1, 2, 3, 4.
for a = A print(a, " ") end

for a ∈ A print(a, " ") end

for a in A print(a, " ") end

1 2 3 4 1 2 3 4 1 2 3 4 

The `continue` keyword lets us skip to the next iteration of a loop.

In [15]:
A = 1:4
for a ∈ A
    if a == 2 continue end
    print(a, " ")
end

1 3 4 

## Functions

We may define functions via assignment or by using the `function` keyword. When using the `function` keyword, the last statement will be the functions return value. The `return` keyword lets us return a value mid-function. The input and output types of a function can be specified via `::`. The following function definitions are all equivalent.

In [16]:
hypotenuse(a::Number, b::Number)::Number = √(a^2 + b^2)
println(hypotenuse(2, 3))

function hypotenuse(a::Number, b::Number)::Number
    √(a^2 + b^2)
end
println(hypotenuse(2, 3))

function hypotenuse(a::Number, b::Number)::Number
    return √(a^2 + b^2)
end
println(hypotenuse(2, 3))

function hypotenuse(a::Number, b::Number)::Number
    return √(a^2 + b^2)
    println("This will never be printed.")
end
println(hypotenuse(2, 3))

3.605551275463989
3.605551275463989
3.605551275463989
3.605551275463989


Functions will return the last executed statement. If we do not want a function to return a value we need to return `nothing`. We may use just the keyword `nothing`, just the keyword `return`, or the combination of both.

In [17]:
function printer()::Number
    a = 4
end
println(printer())

function printer()::Nothing
    a = 4
    return nothing
end
println(printer())

4
nothing


It is possible to compose funcions via the `∘` operator, where `(f ∘ g)(x) = f(g(x))`. Note that function compositions are generally noncommutative.

In [18]:
f(x::Number)::Number = x^2
g(x::Number)::Number = x + 1

c = f ∘ g
d = g ∘ f

println(c(3))
println(d(3))

16
10


Omitting type constraints is equivalent to enforcing the `Any` type. It is a good idea to find a good balance between generality and specificity for type constraints:
* Type constraints provide a way of intrinsic documentation which may reduce the time it takes collaborators to understand our code.
* Overly complicated type constraints may hinder readability and increase the time it takes collaborators to understand our code.
* Ambiguous function definitions may cause bugs. E.g. consider a function using the `*` operator which multiplies numbers and concatenates strings. If such a function is not type constrained it will not raise an error, even if we intended the function to only work with numerical inputs.
* Very specific type constraints may force us to unnecessarily redefine the same function multiple times to cover all relevant cases.
* Counterintuitively, in many common cases, there is no performance penalty for using less specific types, e.g. for `Integer` and `Int64`.
* In some cases, e.g. when working with arrays, not type-constraining a function precisely enough may impact performance ([see this reference](https://docs.julialang.org/en/v1/manual/performance-tips/#man-performance-abstract-container)).

In [19]:
multiply(a, b) = a * b  # Prone to produce bugs.
println(multiply(1, 2))
println(multiply("Hello ", "World!"))  # Does not raise an error :(

2
Hello World!


We should point out that function definitions just add methods to a function object. If we define a function several times with different type constraints we will just add more methods to the function, not overwriting or only partly overwriting previous definitions. This can lead to confusing behavior when writing e.g. a Jupyter notebook where we tend to reuse variable names often.

In [20]:
hypothenuse(a, b) = a * b
println(hypothenuse("2", "3"))
println(hypothenuse(2,3))  # Since the inputs are numbers, Julia will use the definition from a previous cell.
println(methods(hypothenuse))

23
3.605551275463989
# 2 methods for generic function "hypothenuse":
[1] hypothenuse(a::Number, b::Number) in Main at In[16]:14
[2] hypothenuse(a, b) in Main at In[20]:1


## Documentation

Julia docstrings implement the [Markdown](https://docs.julialang.org/en/v1/stdlib/Markdown/) standard. Docstrings may be written directly above functions and types, but also above macros (which we will not cover in an introduction to Julia) and instantiated values (e.g. constants we defined). We use Julia's string syntax for docstrings. Below are examples of docstrings which adhere to the [official docstring recommendations](https://docs.julialang.org/en/v1/manual/documentation/).
> Note: Julia provides advanced documentation functionality such as dynamically generated documentation, which is not covered in this overview.

In [21]:
"Doubles the input Number."
function double_me(x::Number)::Number
    return 2x
end


"""
    some_complicated_function(x)

Do some very complicated things with the inputs.

# Examples
```julia-repl
julia> some_complicated_function(3)
nothing

```
"""
function some_complicated_function(x)
    return nothing
end


""""
    function_with_complicated_arguments(a::String, b::Number, c::Any)::Any

Perform crazy things with questionably complicated inputs.

# Arguments
- `a::String`: the input which does the string stuff.
- `b::Number`: the number of times we do some weird calculation.
- `c::Any`: whatever you want it to be.
"""
function function_with_complicated_arguments(a::String, b::Number, c::Any)::Any
    return nothing
end;  # This semicolon suppresses undesired Jupyter output.

## Arrays

Arrays are part of the Julia standard library. Arrays are of type `Array{T, N}`, where `T` is a supertype of the smallest common type of the array's entries and `N` is the number of array dimensions. Note that we use `display` instead of `println` to pretty-print the defined arrays. Type enforced arrays of type `Array{T, 1}` may be created via the syntax `T[A, B, C, ...]`. If `T` is omitted, the array will fall back to the smallest common type of its entries which is NOT necessarily the `Any` type (contrary to the way this was handled in function definitions).

In [22]:
# An array of type Array{Number, 1}
customarray = Number[1, 2, 3, 4]
display(customarray)

# An array of type Array{Int64, 1}
customarray2 = Int64[1, 2, 3, 4]
display(customarray2)

# We omitted T. The smallest common element type is Int64,
# so the line below creates an array of Type Array{Int64, 1}
customarray3 = [1, 2, 3, 4]
display(customarray3)

4-element Array{Number,1}:
 1
 2
 3
 4

4-element Array{Int64,1}:
 1
 2
 3
 4

4-element Array{Int64,1}:
 1
 2
 3
 4

In [23]:
# In this case the smallest common type of 'String' and 'Int64' is Any,
# so this array will be of type Array{Any, 1}.
customarray2 = Any[1, "Some string", 3, 4]
display(customarray2)

4-element Array{Any,1}:
 1
  "Some string"
 3
 4

Semicolons `;` and newlines concatenate entries vertically. Spaces concatenate entries horizontally. 

In [24]:
# An array of type Array{String, 1}.
stringarray = String["This"; "is"; "an"; "Array."]
display(stringarray)

# Another array of type Array{String, 1}.
stringarray2 = String["This",
                "is",
                "another",
                "Array."]
display(stringarray2)

# A 2-dimensional array of strings, i.e an array of type Array{String, 2}.
stringarray2d = String["A" "2-" "dimensional" "Array."]
display(stringarray2d)

4-element Array{String,1}:
 "This"
 "is"
 "an"
 "Array."

4-element Array{String,1}:
 "This"
 "is"
 "another"
 "Array."

1×4 Array{String,2}:
 "A"  "2-"  "dimensional"  "Array."

Do not confuse commata and concatenation:
* An array defined via `[A, B, C]` will be of type `Array{T, 1}`, where `T` is the smallest common element type of `A`, `B`, and `C` as described above.
* The syntax `[A; B; C]` is shorthand for `vcat(A, B, C)`, i.e the entries `A`, `B`, and `C` will be concatenated along their first dimension.
* The syntax `[A B C]` is shorthand for `hcat(A, B, C)`, i.e. the entries `A`, `B`, and `C` will be concatenated along their second dimension.

In [25]:
# Create an array of type Array{Int64, 3}.
array3d = zeros(Int64, 2, 2, 2)

# T is inferred as Array{Int64, 3}, N is 1.
display([array3d, array3d, array3d])

# T is Int64, N is 3. The size of this array is (6, 2, 2).
display(Int64[array3d; array3d; array3d])

# T is Int64, N is 3. The size of this array is (2, 6, 2).
display(Int64[array3d array3d array3d])

3-element Array{Array{Int64,3},1}:
 [0 0; 0 0]

[0 0; 0 0]
 [0 0; 0 0]

[0 0; 0 0]
 [0 0; 0 0]

[0 0; 0 0]

6×2×2 Array{Int64,3}:
[:, :, 1] =
 0  0
 0  0
 0  0
 0  0
 0  0
 0  0

[:, :, 2] =
 0  0
 0  0
 0  0
 0  0
 0  0
 0  0

2×6×2 Array{Int64,3}:
[:, :, 1] =
 0  0  0  0  0  0
 0  0  0  0  0  0

[:, :, 2] =
 0  0  0  0  0  0
 0  0  0  0  0  0

Imagining elements of type `UnitRange` as vectors similar to 1-dimensional arrays provides intuition for concatenation behaviour.

In [26]:
range = 1:3

# Note the different inferred types for the two arrays below.
display([range, [1; 2; 3]])
display([range, range])

# We may imagine the UnitRange as a vector.
display(Int64[range; [1; 2; 3]])
display(Int64[range [1; 2; 3]])

2-element Array{AbstractArray{Int64,1},1}:
 1:3
 [1, 2, 3]

2-element Array{UnitRange{Int64},1}:
 1:3
 1:3

6-element Array{Int64,1}:
 1
 2
 3
 1
 2
 3

3×2 Array{Int64,2}:
 1  1
 2  2
 3  3

Julia comes with a number of functions to instantiate arrays such as `zeros` for an array filled with zeros and `rand` for an array filled with entries uniformly distributed in the interval \[0, 1\]. We refer to the [official documentation](https://docs.julialang.org/en/v1/manual/arrays/#Construction-and-Initialization) for a comprehensive list of array instantiation functions.

In [27]:
zeroarray  = zeros(Int64, 2, 2)
display(zeroarray)

2×2 Array{Int64,2}:
 0  0
 0  0

## Indexing

The general syntax for indexing into an n-dimensional array is `A[I_1, ..., I_n]`, where `I_i` is a supported index. Supported indices include, but are not limited to

* a scalar index for a specific index in the corresponding dimension,
* a `UnitRange` for multiple indices in the corresponding dimension,
* a colon `:` for all indices in a corresponding dimension.

See the [official documentation](https://docs.julialang.org/en/v1/manual/arrays/#man-supported-index-types) for a comprehensive overview of supported index types.

In [28]:
a = [1 2 3; 4 5 6]
display(a)

first_entry = a[1, 1]
display(first_entry)

first_column = a[:, 1]
display(first_column)

strided_slice = a[:, 1:2:3]  # The UnitRange 1:2:3 contains the elements 1, 3.
display(strided_slice)

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

1

2-element Array{Int64,1}:
 1
 4

2×2 Array{Int64,2}:
 1  3
 4  6

When indexing into strings via single integer, an element of type `Character` will be returned, not an element of type `String`. However, strings are encoded via the UTF-8 encoding and integer indices refer to the corresponding underlying bytes of the encoded character. Since the UTF-8 encoding of a `Character` may consist of multiple bytes, not every integer index is necessarily a valid index into a `String`. The valid integer indices are those referring to the first byte of encoded characters.

In [29]:
some_string = "Disjunct ⟺ A ∪ B = ∅"

println(some_string[10])  # Returns the character ⟺.
println(some_string[13])  # Returns a the space character.
println(some_string[14])  # Returns A.

# This raises a StringIndexError since the index is invalid.
try
    println(some_string[11])
catch e
    if isa(e, StringIndexError) println(e) end
end

⟺
 
A
StringIndexError("Disjunct ⟺ A ∪ B = ∅", 11)


The first and last *valid* index may be indexed via `begin` and `end`, respectively.

In [30]:
println(some_string[begin])  # begin is always 1.
println(some_string[end])  # end the index referring to the first byte of the last encoded character.

D
∅


When using a `UnitRange` as an index into a string a new element of type `String` is returned, not a view of the original string and not a `character`, even if the `UnitRange` contains a single element.

In [31]:
println(some_string[1:8])
println(some_string[1:1])
println(typeof(some_string[1:1]))

Disjunct
D
String


# Iteration

We can iterate over an array with for-loops. If we want to iterate over the valid indices of an array `A`, we iterate over `eachindex(A)`. Note that arrays are stored in column-major order, so the array below is printed as `3546`, not as `3456`.

In [32]:
A = [3 4; 5 6]

for a ∈ A print(a) end
println()
for i ∈ eachindex(A) print(i) end 

3546
1234

Strings behave similarly but iterating over a string iterates over the valid characters, not the byte indices. We illustrate this point by using the `eachindex` method.

In [33]:
some_string = "Disjunct ⟺ A ∪ B = ∅"

for s ∈ some_string print(s) end
println()

for i ∈ eachindex(some_string) print(i, " ") end  # Not equivalent to 1:length(some_string)
println()

# The `length` method measures the number of characters, not the length of the encoded bytes.
for i ∈ 1:length(some_string) print(i, " ") end

Disjunct ⟺ A ∪ B = ∅
1 2 3 4 5 6 7 8 9 10 13 14 15 16 19 20 21 22 23 24 
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 